### ISSUE TITLE
It broke m9

### ISSUE THREAD

**Issue by SimonLight001** [Goerofmuns/blogotron#1]
![image](https://cloud.githubusercontent.com/assets/14348411/16997916/60b39d04-4eaf-11e6-861e-56fadbccd504.png)
this happens when i click on the link

**Comment by SimonLight001** [comment]
it may be cos your pc isnt on??

**Comment by tokamach** [comment]
b9ec49509029f4bc153b86cbc82c6a0da61391d5 should fix it, it's because I messed up the post getting thing

**Comment by tokamach** [comment]
b9ec495 fixed it
